### ISSUE TITLE
Doesn't work in Chrome 46

### ISSUE THREAD

**Issue by kthornbloom** [knoxmodernmedia/detect_autoplay#1]
Thanks for this script! However, this one (and others I've tried) all return false in Chrome 46 on mac which of course does support autoplay. Any clues? I set up a very basic page so nothing would interfere like this:

```
<!doctype html>
<html lang="en">
<meta charset='utf-8'> 
<head>
<body>
    //
</body>
<script type="text/javascript" src="detect_autoplay.js"></script>
<script type="text/javascript">
    if(autoplay){ //if autoplay is supported 
        alert('supported');
    } else {
        alert('not supported');
    }
</script>
</head>
</html>
```

**Comment by norton120** [comment]
Yep, just noticed that this broke in Chrome 46 Linux as well; I'm guessing it has something to do with the update killing autoplay in non-focused tabs; I'll have to dig into it and find a workaround.

**Comment by norton120** [comment]
With a little more testing I found that there was a race condition with the body element. Fixed it in the latest commit, should be good to go.
